### ISSUE TITLE
trimetric docker will not start 

### ISSUE THREAD

**Issue by forever-and-a-day** [bsdavidson/trimetric#2]
The following error occurs when attempting to start trimetric: 
```

Building api
Step 1/8 : FROM golang:1.9
 ---> ef89ef5c42a9
Step 2/8 : RUN go get github.com/githubnemo/CompileDaemon
 ---> Using cache
 ---> f99fe34e8ad1
Step 3/8 : RUN go get github.com/lib/pq
 ---> Running in 0d8128d0a62d
# github.com/lib/pq
src/github.com/lib/pq/notify.go:47:2: undefined: driver.Connector
ERROR: Service 'api' failed to build: The command '/bin/sh -c go get github.com/lib/pq' returned a non-zero code: 2

```
Note that the script was run with root privileges, as dockerd will not start without them.

**Comment by zrsmithson** [comment]
`pq` no longer works with `golang:1.9`. I got around this by changing to the latest version in `Dockerfile-api`. I also had a warning for the install trimetric line, so I had to add @latest. I'll submit a PR if it didn't seem to break anything else, otherwise I'll find the right version of `pq` to link to

```
# Dockerfile-api
FROM golang:1.17

RUN go get github.com/githubnemo/CompileDaemon
RUN go get github.com/lib/pq

COPY . /go/src/github.com/bsdavidson/trimetric/
RUN go install github.com/bsdavidson/trimetric/cmd/trimetric@latest

VOLUME ["/go/src/github.com/bsdavidson/trimetric"]
EXPOSE 80

CMD [ "/go/bin/trimetric" ]
```
